apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Tr3V3rn/currencyconverter-lab.git'
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://28624FF24BBA4B30BCC6AB697BD8E7C5.gr7.us-east-2.eks.amazonaws.com
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
