---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgAIzCGXVC282vlqTl893doIMSwFTK8znycym5E07d+R70IEz9XhpFN8muswiLRWyWhGGKb/vvQB0mZ4E2vUki2q2gsIywjkbdSPYlIZ4pdegbI5ARLngaQjy9hjhM/3cHCqsMPYtOIAtKqsyAMc7fqAyzWQ3fBKqhIXI6aOhgXqfi8Kl4dALic90MiSr67BOdU8ngGpCaQewsbpRcJs+QcVtCaMg0R/jVxoP2ygcbKK93vFV4/4RKNoEEQzxmx2mV4KwatXV8S0dwt68m0qM4BavFDCI+/rzZj13oSwGTVg4uALnj9cNtnsdci4zT6ZeRSJVZN1OqTxznvfiGL9yTTPojL0dIuwqwNHtjicAmU1gdUNEkKHIEsJUAP9TdRqM3maqJ0dAlnLlqaHsfs1Dq7wskNsemykG+jssW1qkAZuGrrw+be2VbRKcEQckwP3V2S9mC2rkJVS1xzmXekJO0UQXG6CM+gKoUujNClKGONZ7Wca0wHsb1Szu9gb277edp/uS1ozWnwtynGptBphjrybGCXNfbJfJbFvsSiO6REzuBfkjGBzs+NjYO69hkuiLcT8hNJs9uNgBTXXp0H9gCtp/IafFBIP+989uLr4PCzj4LOaGNeGYqcZXpFYd5QfDyef5nRox5sClOtPB/gmFNzUXjw8SkikvVLWwXEkK8i6vFoAuWtydlF6xLOJ7JB0i/XkSzGxAB3+Y93i2bO8ySLYQkcoohnF/g+Q5aJ0hRLNwIsDcQSdZEdl2oSlqafg1wt29g==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque