---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgBPgUKLSvkABuAklru7WDhH5Iu2vr2xeD+Aux3aRT8KzIwYvuaGLphv5ljhtz+K2yEBvZQ0iFnvcxtmM3Mg1KO5tminlL6Rh6R4ylu9qlB1dgp50JQ7fmJtTtMHjspP9oTrOBSywK1j3wIv8gVlhaMdQ/gb6eSMK0y/GzS6Gr2O7AixNRvqxgye0C9oFLrl/ttGO4r9AtSQnNaTJu2J8uQy1OuITuxy76pllrCoZwePS8CxxD9HyAD0RilMBKo0SLu/+w5v7muYS+YXFIJATabqSTMJnvwRfXhfnlcFjiAkV1sAjr4w7786+EiE7MIVLis6SEGivPGH5eLo5g5FeLInly2lJOaL32fjnVLHCYV4OkHXIUsF4hr6HaBXbxbf327Fw+3vXsVkjdPkhpZOP8abB1t1/ra/z1Iw8ZpZA0BDDgCbEuMAcVAe3NHSQCapWxQ4GtBKcPZSjRPqaawV1jKX3y9NUfvOUih6W0lDuV9BmfWwwLdLXP49kaQwId7kl9TdPSPTk72NWSa7TJAQAdc5UANQLNDQLfJ94x/hknIi10aqCApR2hNiiyvKhbfgc90gH2FEoubLFrLy4/RIi5LYM6x2mFLfxMRL4jvTeKeVJQhTWaeQE4vcvX2vYxoG4HvadgS6lLx9eamaKvW/doftS+5uRwxXjG4EaahA7dvATxRFeb09hx+GOlwsESHucaiAaE2N/pPXw2VWvV3AyNXbyHSrML/MtHX1DPB75Bq8JZJEVxs0HjCPoCBvRF9kduX+sg==
  template:
    metadata:
      name: api-keys
      namespace: default
    type: Opaque
